version: '3.3'

services:
  backend:
    build:
      context: ./backend
      args:
        port: 3000
    image: hackatum/backend:dev
    volumes:
      - "./backend:/usr/app:rw"
    ports:
      - "127.0.0.1:3000:3000"
    #restart: always
    user: ${CURRENT_UID}
    networks:
      - internet_sim

  backend_frontend:
    build:
      context: ./backend_frontend
      args:
        port: 5000
    image: hackatum/backend_frontend:dev
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
     - "./backend_frontend:/usr/app:rw"
    user: ${CURRENT_UID}
    networks:
      - internet_sim

  #car:
  #  build:
  #    context: ./car
  #    #args:
  #    #  port: 3000
  #  image: hackatum/car:dev
  #  volumes:
  #    - "./car:/usr/app:rw"
  #  ports:
  #    - "127.0.0.1:1234:1234"
  #  #restart: always
  #  user: ${CURRENT_UID}
  #  networks:
  #    - internet_sim


networks:
  internet_sim:
